version: '3'

services:
  admin-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3200:3000
    networks:
      - samagra_compass

networks:
  samagra_compass:
    external: true
